### ISSUE TITLE
feat: Enforce highest quality audio

### ISSUE THREAD

**Issue by mekrishna11** [rabilrbl/jiotv_go#102]
### Feature description

i have set environment variable JIOTV_FORCE_HIGHEST_QUALITY=true and try m3u8 /live/high/143.m3u8 but it doesn't make any change on audio quality hope it will update on next update thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
There is no option to set Audio as highest, when you go `/live/high/143.m2u8` you automatically get high audio. 
There is no option in JioTV API to do the same.

Closing.
