### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by pratiks360** [rabilrbl/jiotv_go#14]
<img width="824" alt="image" src="https://github.com/rabilrbl/jiotv_go/assets/6492613/1e7dc985-a060-4fb8-8326-94153722588f">
with windows amd64 version

**Comment by rabilrbl** [comment]
Are you using any VPN? Or Cloudflare warp?

**Comment by pratiks360** [comment]
Yes. Outside of india

**Comment by rabilrbl** [comment]
Currently, JioTV Go is not supported outside India and VPN networks
