### ISSUE TITLE
Bug: Buffering Problems with Some HD Channels on IPTV Apps

### ISSUE THREAD

**Issue by siddharthsky** [rabilrbl/jiotv_go#16]
There is an issue while playing **some HD channels** as they are not playing smoothly when accessed through IPTV using M3U playlist. The SD channels work perfectly, but some HD channels consistently encounter buffering problem and often load halfway without playing at all.

Steps to Reproduce:
1.  Add playlist to any IPTV [player](https://play.google.com/store/search?q=iptv%20player&c=apps)
2.  Attempt to play HD channels. 
    *   History TV18 HD
    *   Colors HD
    *   SET HD
    *   MTV Beats HD etc

Additional Information:
This issue is consistently reproducible across different devices and IPTV player apps.
I also have checked my internet connection, which has sufficient bandwidth to handle HD steams xD. HD streams for these channels work perfectly fine when played directly from the website (localhost), highlighting that the issue is specific to IPTV playback.

**Comment by rabilrbl** [comment]
Test it on VLC PC and tell me results

**Comment by rabilrbl** [comment]
@siddharthsky On VLC, it works smoothly. I tried on android IPTV players, I can't even play...When I click on a channel, It's stuck at loading

**Comment by siddharthsky** [comment]
> @siddharthsky On VLC, it works smoothly. I tried on android IPTV players, I have refactored all `.m3u8` regex string processing to address buffering issues. I have tested everything works fine for me.

@rabilrbl 
Tried on VLC, everything works. 
On IPTV, still same issue as mentioned. (for HD channels)

------------ 

and from v5.4 (https://github.com/rabilrbl/jiotv_go/issues/11#issuecomment-1703176776)

**Comment by rabilrbl** [comment]
@siddharthsky  I am testing on OTT navigator, as you said some HD channels are not playable. I'll debug and check

**Comment by rabilrbl** [comment]
@siddharthsky feel free to re-open issue until problems are fixed

**Comment by siddharthsky** [comment]
For now, in the OTT navigator > Player > Setup codec preferences > Codec settings > change it to (Exo V1 or VLC). This seems to resolve the buffering issue.

**Comment by rabilrbl** [comment]
@siddharthsky I have reviewed almost everything, looks like the m3u8 from JioTV API is not supported by some player codecs. Unsure how to proceed ahead.

**Comment by rabilrbl** [comment]
@siddharthsky, I have reviewed almost everything. It appears that the m3u8 from the JioTV API is not supported by certain player codecs. I am unsure how to proceed from here

**Comment by SP4RKiOP** [comment]
Is there any other version of jiotv api? Any older version working as of now? Coz earlier it worked.

**Comment by rabilrbl** [comment]
@SP4RKiOP I don't think so. What do you mean by earlier it worked? Where?

**Comment by spacex97** [comment]
there are changes done by jio in codec of these channels due to which hardware codec is not able to play them correctly, the only option is to use exo v1 codec in iptv apps and if you iptv app does not have this option then you need to switch the app.
This issue does not persist due to jiotv_go code, @rabilrbl you can close this since we cannot do anything in this regards.

**Comment by rabilrbl** [comment]
Thanks @spacex97

**Comment by rabilrbl** [comment]
Solution after #96 was merged!

Delete the current m3u playlist on IPTV App and download new playlist with this url 
`http://localhost:5001/playlist.m3u?q=high`
Where high is resolution, change according to your internet bandwidth to: `low` or `medium`
