### ISSUE TITLE
feat: combination of language and genre in group-title in m3u for better grouping of channels

### ISSUE THREAD

**Issue by barelycodes** [rabilrbl/jiotv_go#174]
### Feature description

Channels are currently grouped based on genre. This makes the list of channels quite long even in groups. If a combination of language and genre is used for grouping then it will be easier to navigate. For example, Hindi Entertainment, English Entertainment, Hindi News, English News, etc. instead of just Entertainment, News respectively.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by technofreak24** [comment]
> Combination of language and genre is used for grouping then it will be easier to navigate. 

In Python Addon filtering is done by **Languages**, **Categories**, **Broadcasters**, **Language + Category** (combo match).
Languages, Categories visibility can be turned ON/OFF in Settings.

![jtv1_083024](https://github.com/rabilrbl/jiotv_go/assets/121749085/1d570757-14ab-4688-8312-4c0a3efdb830)

![jtv2_083042](https://github.com/rabilrbl/jiotv_go/assets/121749085/908d0453-7ed2-484f-8ef1-4e89eb481d61)
