### ISSUE TITLE
bug: Not able to run binary

### ISSUE THREAD

**Issue by firefoxOnFire** [rabilrbl/jiotv_go#183]
### Bug description

I was trying to run on github codespace and got this error.

### Steps to reproduce

after downloading the binary from github and running ./binary

### Relevant log output

```shell
./jio: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./jio)
./jio: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./jio)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
This problem is related to c libs in go.
You need to compile JioTV Go on github codespaces itself.
Also JioTV Go won't work outside residential IP. i.e. won't work on datacenter IPs and outside India
