### ISSUE TITLE
bug: unable to play sony channels now

### ISSUE THREAD

**Issue by piyushgarg** [rabilrbl/jiotv_go#187]
### Bug description
other channels are working fine except sony channels
unable to play some of the sony channels, check the screenshot below ⬇️

### Steps to reproduce

Click on any sony channel sab, set, sony sports etc

### Relevant log output

```shell
NA
```

### Screenshots or videos

![image](https://github.com/rabilrbl/jiotv_go/assets/246124/313ef1e5-335d-4fa3-8169-56adfe47cb38)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Sony channels are now not live. Instead shows are played directly from SonyLiv CDN
It's hard to implement live channel based on current JioTV Go structure.

**Comment by rabilrbl** [comment]
Temporary fix for sony channels:

You will be able to watch sony channels,
Shows will start at beginning, you can seek forward and backward like a regular video.

Once the show is ended in EPG. Refresh the page new show will be loaded.

Sony Sports channels are f-ed.
