### ISSUE TITLE
bug: Add Sony BBC Earth

### ISSUE THREAD

**Issue by rohit267** [rabilrbl/jiotv_go#200]
### Bug description

Other versions has Sony BBC Earth

### Steps to reproduce

Search for Sony BBC Earth

### Relevant log output

```shell
n/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by piyushgarg** [comment]
It was there last week but with recent changes it is not available now and other like pix
