### ISSUE TITLE
feat: Hindi Sony BBC Earth Channel

### ISSUE THREAD

**Issue by rohit267** [rabilrbl/jiotv_go#219]
### Feature description

Sony BBC Earth Channel is in English

### Solution

Try to add Hindi audio

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
The existing one is from Sony Liv
If you have the link of Sony BBC Earth Hindi, re-open this issue and post here.
