### ISSUE TITLE
bug: Logos not displaying 

### ISSUE THREAD

**Issue by RandomGithubUsername** [rabilrbl/jiotv_go#220]
### Bug description

Seeing 500 errors on logo paths (both on webui and playlist)

### Steps to reproduce

Open webui and notice no logos are displayed

### Relevant log output

```shell
n/a
```

### Screenshots or videos

<img width="1004" alt="webui" src="https://github.com/rabilrbl/jiotv_go/assets/26655510/decb2669-7878-4c42-92a8-21b57c31684a">

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
No issues here.

Here are the possible reasons:
- Your ISP (internet service provider) might be blocking
- You may have a DNS error, try changing it to cloudflare or anything which isn't default.

**Comment by RandomGithubUsername** [comment]
I identified the issue, (only the) images URL prefix is http instead of https (both work fine) and if your server/network/firewall is configured to block connections to non HTTPS hosts, images will not load. I created a PR to fix this issue https://github.com/rabilrbl/jiotv_go/pull/221

**Comment by rabilrbl** [comment]
@RandomGithubUsername thanks for the correction. Much appreciated 👍
