### ISSUE TITLE
feat: m3u8 file generating feature

### ISSUE THREAD

**Issue by bikash0070** [rabilrbl/jiotv_go#230]
### Feature description

Hello team, 

I really appreciate your smooth-running script that doesn't buffer, but I've noticed that generating high playlists does not work on Samsung TVs to automatically get high-quality playback on Tarzan version TVs. I was wondering if you could help us find a link like the one I've seen in other scripts. 

Thank you. 
e.g: "jioo/app/strmm.php?cid=144&id=Colors_HD_MOB-audio_98835_eng=98800-video=2293600.m3u8" if possible please make from this our generate type e.g "render.m3u8?auth=YiZBgCBhSv8MVa-j6rnBwK6-r-IRTr0RbUF2S3-_KctjzyjBVjbzVn2PAHxjFveDMr7xmbLPRzR67E34hAip11tR1uiGiwMyMCpWCILyB-JMD0r9uVbX8PHkfqTm2v7p_dqaGHvDQEj62_jg9Zte49uXGfKNYvfnDRoja8aAp3QzsPrQut5qU3-cQZxo1K4o6d2uVwZ9Ao2ZuoSY4QDugDvna40lcGqLUsH-jqPh2M4H25q8yxA0sfHxW72GjMjmMCrY7BaQDonq3_ZTPvbGIFbUNKcZ79U4iGCi4l2Of-dBdyzW563X73_mslNcXxAZAlX0cEFQvib86-VGIXncd8Vzvl4XVkeqyB9xan7y4E-L5rFaVbiP6s3XUblHgc3NoNiyvqjy7mCVQ5T8CJXOpcmeXe4lr2U=&channel_key_id=146" which expire after sometime or can you help me to me fix that link never expire so i can use link using idm.

### Solution

looking for help 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
JioTV Go is different from other projects you have seen.

For any channel id, access m3u8 at `http://localhost:5001/live/high/143.m3u8`
