### ISSUE TITLE
bug: Most channels no longer working

### ISSUE THREAD

**Issue by RandomGithubUsername** [rabilrbl/jiotv_go#253]
### Bug description

Seeing 419 errors. Some channels (like CNBC prime) play fine.

### Steps to reproduce

Try playing History HD

### Relevant log output

```shell
n/a
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Everything's fine

![Screenshot_2024-01-27-07-27-47-59_4d38fce200f96aeac5e860e739312e76](https://github.com/rabilrbl/jiotv_go/assets/63334479/62f2da5e-d5f2-4d7b-a40f-af298a3bec36)



Simply logout and login again to refresh your login credentials

**Comment by RandomGithubUsername** [comment]
Yup you are right, re-login fixed it! Thanks! :)
