### ISSUE TITLE
feat: EPG interval filter

### ISSUE THREAD

**Issue by vishalkrv** [rabilrbl/jiotv_go#254]
### Feature description

Can we please add filter to epg file . eg localhost:5001/epg.xml.gz?interval=6h. Because the current epg file is big, my tv fails at parsing the EPG file. So some kind of filter will be helpful

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
That will be a lot of hard coding required because JioTV API gives 24hr in each call.

Also please post logs about epg failing on your TV

**Comment by vishalkrv** [comment]
I use a third party app (https://m3u-ip.tv/) on Samsung TV to play IPTV. It has some limit around 20,000 programs in EPTV, so with 24hr interval the program list goes beyond 37000 and the app stucks. 

It will be good to have feature.

**Comment by rabilrbl** [comment]
I want you to do one thing,
Disable EPG completely with following command
```
jiotv_go epg del
```
If you set EPG config value, make sure that is false too.

Then use a third party EPG as mentioned here
https://avkb.short.gy/jioepg.xml.gz

Doc guide: https://jiotv_go.rabil.me/usage/android_tv.html#third-party-epg-providers


Let me know the results here

**Comment by rabilrbl** [comment]
@vishalkrv I will close this on stale. Please report

**Comment by rabilrbl** [comment]
Closing this as stale. Re-open this issue, if required
