### ISSUE TITLE
bug: Channel not working

### ISSUE THREAD

**Issue by devilxsam** [rabilrbl/jiotv_go#278]
### Bug description

when i play channel no 2258 name Animex channel not playing web and using m3u8 playlist link

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Please re login and check

Everything works on my end.
Re open this issue if problem doesn't solve with appropriate logs and screenshots
