### ISSUE TITLE
bug: jiotv_go: line 1: Not: command not found

### ISSUE THREAD

**Issue by ganpats** [rabilrbl/jiotv_go#281]
### Bug description

I installed it on macbook M1 using Automatic Install Script, when I run `jiotv_go help` command on terminal, I got below error:
`jiotv_go: line 1: Not: command not found`

### Steps to reproduce

Step 1: Install on Mac M1 with Automatic Install Script.
Step 2: Run `jiotv_go help` command on terminal.

### Relevant log output

```shell
On Terminal:

jiotv_go help
/jiotv_go: line 1: Not: command not found
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SritharBoss** [comment]
exit the terminal and open it again. So that your terminal will pulls all the updated installed packages from your device.
