### ISSUE TITLE
feat: Support for Non-residential VPN (think there's a workaround)

### ISSUE THREAD

**Issue by elvistony** [rabilrbl/jiotv_go#295]
### Feature description

I've tested multiple solutions for getting this service to work outside India and (most) worked only when I used my personal home proxy (back home). Until I tried out this repo: [TS-JioTV](https://github.com/mitthu786/TS-JioTV). I tried it on a VPN hosted on AWS Mumbai and it works!

I've been out of the game for too long and I did try to tinker around the URLs from that Repo to yours, but I couldn't seem to figure it out.

### Solution

I've tested this repo and it seems to work well with my non-residential VPN and we might be able to replicate those API calls to make it work for this repo too! 

### Additional context

I was an author of the (now defunct) `jio-pyserver` (you might find forks🤷‍♂️) and always loved exploring how various APIs interacted.  I really liked the robustness of your app especially since its very easily deployable!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
@elvistony Thanks for the assessment. Currently I get no time to focus on this project, I'll take a look in my free time.

If you are certain that this works on AWS Mumbai (asia-south1) then we need to update docs.

**Comment by rabilrbl** [comment]
@elvistony If u actually have tested JioTV Go on a non-residential VPN, tell us the VPN provider or Service provider

**Comment by rabilrbl** [comment]
Closing as stale, no response from author
