### ISSUE TITLE
feat: its possible to host it on Heroku etc. platforms

### ISSUE THREAD

**Issue by SamyBotz** [rabilrbl/jiotv_go#305]
### Feature description

feat: its possible to host it on Heroku etc. platforms

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Nope. Not Possible.
Next time, read the documentation correctly
