### ISSUE TITLE
Server stops after some time with error "concurrent map iteration and map write"

### ISSUE THREAD

**Issue by dheerajv4855** [rabilrbl/jiotv_go#32]
Hi, 
go server is stopping after changing some channels with error saying 
"concurrent map iteration and map write"
![Screenshot from 2023-09-08 22-15-25](https://github.com/rabilrbl/jiotv_go/assets/48526859/51728e60-1445-48c9-842a-78ac6f91f531)

**Comment by siddharthsky** [comment]
The issue is related to GIN, check open issue https://github.com/gin-gonic/gin/issues/3387

             The issue should be solved when migrating to go fiber #30

_Originally posted by @rabilrbl in https://github.com/rabilrbl/jiotv_go/issues/31#issuecomment-1710412423_

**Comment by rabilrbl** [comment]
Duplicate of #31
