### ISSUE TITLE
feat: Sony Channels are not working. Please add a feature to view sony channels.

### ISSUE THREAD

**Issue by prateek440jain** [rabilrbl/jiotv_go#332]
### Feature description

feat: Sony Channels are not working. Please add a feature to view sony channels.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
on it

**Comment by rabilrbl** [comment]
Please refer https://telegram.me/jiotv_go/71
