### ISSUE TITLE
bug: Does not work behind VPN?

### ISSUE THREAD

**Issue by priyanshuz** [rabilrbl/jiotv_go#333]
### Bug description

I am trying to use it from outside the country, but I do have VPN tunnel to India. and it does not seem to work. 

Below is what I get when trying to connect it via VPN.

panic: Request failed with status code: 450
goroutine 38 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
github.com/gofiber/fiber/v2/middleware/recover.defaultStackTraceHandler(0xafcc05?, {0x1060700, 0xc000262b40})
        github.com/gofiber/fiber/v2@v2.52.4/middleware/recover/recover.go:12 +0x25
github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.New.func1.1()
        github.com/gofiber/fiber/v2@v2.52.4/middleware/recover/recover.go:31 +0x74
panic({0x1060700?, 0xc000262b40?})
        runtime/panic.go:770 +0x132
log.(*Logger).Panicf(0xc0001f2f60, {0x112b612?, 0xc000084e00?}, {0xc000035288?, 0x110c465?, 0x3?})
        log/log.go:310 +0x6e
github.com/rabilrbl/jiotv_go/v3/pkg/television.Channels()
        github.com/rabilrbl/jiotv_go/v3/pkg/television/television.go:202 +0x59a
github.com/rabilrbl/jiotv_go/v3/internal/handlers.IndexHandler(0xc0002a0008)
        github.com/rabilrbl/jiotv_go/v3/internal/handlers/handlers.go:81 +0x2a
github.com/gofiber/fiber/v2.(*App).next(0xc00013d408, 0xc0002a0008)
        github.com/gofiber/fiber/v2@v2.52.4/router.go:145 +0x1be
github.com/gofiber/fiber/v2.(*Ctx).Next(0x0?)
        github.com/gofiber/fiber/v2@v2.52.4/ctx.go:1030 +0x4d
github.com/gofiber/fiber/v2/middleware/etag.New.func1(0xc0002a0008)
        github.com/gofiber/fiber/v2@v2.52.4/middleware/etag/etag.go:33 +0xb7
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0002a0008?)
        github.com/gofiber/fiber/v2@v2.52.4/ctx.go:1027 +0x3d
github.com/gofiber/fiber/v2/middleware/helmet.New.func1(0xc0002a0008)
        github.com/gofiber/fiber/v2@v2.52.4/middleware/helmet/helmet.go:92 +0x53f
github.com/gofiber/fiber/v2.(*App).next(0xc00013d408, 0xc0002a0008)
        github.com/gofiber/fiber/v2@v2.52.4/router.go:145 +0x1be
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000229da0?)
        github.com/gofiber/fiber/v2@v2.52.4/ctx.go:1030 +0x4d
github.com/gofiber/fiber/v2/middleware/logger.New.func3(0xc0002a0008)
        github.com/gofiber/fiber/v2@v2.52.4/middleware/logger/logger.go:119 +0x316
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0000d0518?)
        github.com/gofiber/fiber/v2@v2.52.4/ctx.go:1027 +0x3d
github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.CORS.func2(0xc0002a0008)
        github.com/rabilrbl/jiotv_go/v3/internal/middleware/cors.go:30 +0x147
github.com/gofiber/fiber/v2.(*Ctx).Next(0x17c4fe0?)
        github.com/gofiber/fiber/v2@v2.52.4/ctx.go:1027 +0x3d
github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.New.func1(0x10860c0?)
        github.com/gofiber/fiber/v2@v2.52.4/middleware/recover/recover.go:43 +0xbb
github.com/gofiber/fiber/v2.(*App).next(0xc00013d408, 0xc0002a0008)
        github.com/gofiber/fiber/v2@v2.52.4/router.go:145 +0x1be
github.com/gofiber/fiber/v2.(*App).handler(0xc00013d408, 0xb970af?)
        github.com/gofiber/fiber/v2@v2.52.4/router.go:172 +0x78
github.com/valyala/fasthttp.(*Server).serveConn(0xc00014cd88, {0x134cd90, 0xc000052cf8})
        github.com/valyala/fasthttp@v1.54.0/server.go:2379 +0xe70
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0000da320, 0xc00024b620)
        github.com/valyala/fasthttp@v1.54.0/workerpool.go:224 +0xa4
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        github.com/valyala/fasthttp@v1.54.0/workerpool.go:196 +0x32
created by github.com/valyala/fasthttp.(*workerPool).getCh in goroutine 1
        github.com/valyala/fasthttp@v1.54.0/workerpool.go:195 +0x190

### Steps to reproduce

1. Connect to VPN to India
2. Run the application 
3. Try to browse 

### Relevant log output

```shell
panic: Request failed with status code: 450
goroutine 38 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
github.com/gofiber/fiber/v2/middleware/recover.defaultStackTraceHandler(0xafcc05?, {0x1060700, 0xc000262b40})
        github.com/gofiber/fiber/v2@v2.52.4/middleware/recover/recover.go:12 +0x25
github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.New.func1.1()
        github.com/gofiber/fiber/v2@v2.52.4/middleware/recover/recover.go:31 +0x74
panic({0x1060700?, 0xc000262b40?})
        runtime/panic.go:770 +0x132
log.(*Logger).Panicf(0xc0001f2f60, {0x112b612?, 0xc000084e00?}, {0xc000035288?, 0x110c465?, 0x3?})
        log/log.go:310 +0x6e
github.com/rabilrbl/jiotv_go/v3/pkg/television.Channels()
        github.com/rabilrbl/jiotv_go/v3/pkg/television/television.go:202 +0x59a
github.com/rabilrbl/jiotv_go/v3/internal/handlers.IndexHandler(0xc0002a0008)
        github.com/rabilrbl/jiotv_go/v3/internal/handlers/handlers.go:81 +0x2a
github.com/gofiber/fiber/v2.(*App).next(0xc00013d408, 0xc0002a0008)
        github.com/gofiber/fiber/v2@v2.52.4/router.go:145 +0x1be
github.com/gofiber/fiber/v2.(*Ctx).Next(0x0?)
        github.com/gofiber/fiber/v2@v2.52.4/ctx.go:1030 +0x4d
github.com/gofiber/fiber/v2/middleware/etag.New.func1(0xc0002a0008)
        github.com/gofiber/fiber/v2@v2.52.4/middleware/etag/etag.go:33 +0xb7
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0002a0008?)
        github.com/gofiber/fiber/v2@v2.52.4/ctx.go:1027 +0x3d
github.com/gofiber/fiber/v2/middleware/helmet.New.func1(0xc0002a0008)
        github.com/gofiber/fiber/v2@v2.52.4/middleware/helmet/helmet.go:92 +0x53f
github.com/gofiber/fiber/v2.(*App).next(0xc00013d408, 0xc0002a0008)
        github.com/gofiber/fiber/v2@v2.52.4/router.go:145 +0x1be
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000229da0?)
        github.com/gofiber/fiber/v2@v2.52.4/ctx.go:1030 +0x4d
github.com/gofiber/fiber/v2/middleware/logger.New.func3(0xc0002a0008)
        github.com/gofiber/fiber/v2@v2.52.4/middleware/logger/logger.go:119 +0x316
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0000d0518?)
        github.com/gofiber/fiber/v2@v2.52.4/ctx.go:1027 +0x3d
github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.CORS.func2(0xc0002a0008)
        github.com/rabilrbl/jiotv_go/v3/internal/middleware/cors.go:30 +0x147
github.com/gofiber/fiber/v2.(*Ctx).Next(0x17c4fe0?)
        github.com/gofiber/fiber/v2@v2.52.4/ctx.go:1027 +0x3d
github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer.New.func1(0x10860c0?)
        github.com/gofiber/fiber/v2@v2.52.4/middleware/recover/recover.go:43 +0xbb
github.com/gofiber/fiber/v2.(*App).next(0xc00013d408, 0xc0002a0008)
        github.com/gofiber/fiber/v2@v2.52.4/router.go:145 +0x1be
github.com/gofiber/fiber/v2.(*App).handler(0xc00013d408, 0xb970af?)
        github.com/gofiber/fiber/v2@v2.52.4/router.go:172 +0x78
github.com/valyala/fasthttp.(*Server).serveConn(0xc00014cd88, {0x134cd90, 0xc000052cf8})
        github.com/valyala/fasthttp@v1.54.0/server.go:2379 +0xe70
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0000da320, 0xc00024b620)
        github.com/valyala/fasthttp@v1.54.0/workerpool.go:224 +0xa4
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        github.com/valyala/fasthttp@v1.54.0/workerpool.go:196 +0x32
created by github.com/valyala/fasthttp.(*workerPool).getCh in goroutine 1
        github.com/valyala/fasthttp@v1.54.0/workerpool.go:195 +0x190
```

### Screenshots or videos

<img width="899" alt="screenshot1" src="https://github.com/rabilrbl/jiotv_go/assets/30660828/da389989-5640-477a-961a-20f4c202369d">

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Birarvindersingh** [comment]
I am facing the same issue as well. What VPN are you using, by the way?

**Comment by priyanshuz** [comment]
Surfshark. It appears that Jio might have blocked Surfshark India VPN locations.

What VPN are you using?

**Comment by Birarvindersingh** [comment]
I tried it with ProtonVPN and Express VPN, but it wasn't working.

**Comment by priyanshuz** [comment]
I see. Maybe it could be something else.

**Comment by rabilrbl** [comment]
JioTV APIs are blocked on datacenter IPs. None of major VPN providers will work.

Closing
