### ISSUE TITLE
bug: Third-Party EPG doesn't update

### ISSUE THREAD

**Issue by vsumavane** [rabilrbl/jiotv_go#340]
### Bug description

In the Documentation, for Android TV, you mentioned a third party EPG link because Android TV has issue loading EPG by itself. The Third Party EPG link provided doesn't update and hasn't updated from last 2 months.

### Steps to reproduce

Step 1 :Update EPG in TiviMate App on Android TV with the link : https://avkb.short.gy/jioepg.xml.gz
Step 2: Check whether the latest EPG has been updated.

### Relevant log output

```shell
n/a
```

### Solution

I have made my own EPG link which I update and intend to update every 24 hours with a bot. I assure that this link will be updated every day for next few months as this project directly affects everyday TV for myself.
link : https://fomy.short.gy/epg.xml.gz
The above link is managed by me on my repo : https://github.com/vsumavane/EPG_list

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
U decided not to maintain?

**Comment by TecnikOfficial** [comment]
> > U decided not to maintain?
> 
> No, it's not like that, in the recent update, it seems the bug of EPG in Android TV has been fixed. I thought the third party EPG would not be needed anymore. But I still will be maintaining it.

i m using ur epg in tivimate but in ott naviagtor its fixed . for tivimate still 3rd party is epg is required

**Comment by vsumavane** [comment]
Thank you for bringing this to my attention! I appreciate your understanding. I’ll make sure to restart maintaining the EPG link to ensure it works properly from now on. If you have any more issues or need further assistance, please feel free to let me know.

**Comment by rabilrbl** [comment]
EPG is manged by client and not by JioTV Go.
For example, if your using OTT Navigator IPTV client, then their responsible.
Thanks
