### ISSUE TITLE
display jiotv_go version during startup

### ISSUE THREAD

**Issue by piyushgarg** [rabilrbl/jiotv_go#351]
### Feature description

display jiotv_go version during startup
put Fiber version in logs and jiotv_go version here.

![image](https://github.com/user-attachments/assets/340e4df5-86d8-428c-a19c-59993d2ba521)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
I dont think we can remove fiber logs, but lets see what can I do
