### ISSUE TITLE
feat: Add support for LG WebOS tv 

### ISSUE THREAD

**Issue by dheerajv4855** [rabilrbl/jiotv_go#354]
### Feature description

In LG webOS it is not loading playlist in M3U IPTV app 
but working on same app on android tv 
this could be due to not able to download playlist on lg tv, so to fix this allow streaming of playlist instead of downloading as a file

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
No logs, no detailed explanation of the error. No screenshots.

How can we help? Please include all the details along with device architecture and device OS

**Comment by ladlavj** [comment]
I would like add some detail to the problem with playlist URL.. It works when playlist is downloaded as file and doesn’t work when provided direct playlist url to the player on WebOs. I am using IPTV M3U where it doesn't work as url and works if I provide downloaded file to MY TV app.

![image](https://github.com/user-attachments/assets/08a818a1-c297-4f25-be4c-a7d359eb76bf)

**Comment by dheerajv4855** [comment]
hi @ladlavj 
thanks for the details 
i didnt get time to collect the details 
i have modified the code to stream the playlist instead of downloading at once 
and it is working fine in my lg webos tv 
@rabilrbl pls let me know if you want PR for that change

**Comment by ladlavj** [comment]
@dheerajv4855 is it possible to use your version?

**Comment by dheerajv4855** [comment]
hi @ladlavj @rabilrbl 
created a PR to fix lg webos tv issue in this PR https://github.com/rabilrbl/jiotv_go/pull/371
