### ISSUE TITLE
feat: Add JIOTV Go to the UNRAID App Store

### ISSUE THREAD

**Issue by aasimenator** [rabilrbl/jiotv_go#374]
### Feature description

I use UNRAID for my home server and would like to set up JIOTV Go on this server as a docker container and use it as a service for TVs in my home. I've tried to play around with adding the app manually but it doesn't work correctly therefore would like to request if possible to add the JioTV Go to the "Apps" section in UnRAID so users can easily click install it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
I am not planning on adding JioTV Go to any third party app store, as it will only increase the burden for maintenance.

If ur facing issues in running JioTV Go. Join the community support group in Telegram to discuss about the isssue.
