### ISSUE TITLE
bug: failed to listen: listen tcp4

### ISSUE THREAD

**Issue by rishav12s** [rabilrbl/jiotv_go#376]
### Bug description

ran jiotv_go serve and it doesnt start and shows this

`failed to listen: listen tcp4: lookup localhost on 192.168.0.1:53: no such host`

### Steps to reproduce

`jiotv_go serve`

### Relevant log output

```shell
n/a
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
The bug is not able to reproduce. Please do a discussion in community support group.

Thank you!
