### ISSUE TITLE
bug: Sony Channels not showing Live TV

### ISSUE THREAD

**Issue by PadekarPratap** [rabilrbl/jiotv_go#379]
### Bug description

I'm using [CustTermux-JioTVGo](https://github.com/siddharthsky/CustTermux-JioTVGo) for watching Jio TV on my Android TV. All Channels are working fine except the Sony channels. When I try to run any Sony channel, it just shows me a pre-recorded show which is not live. 

### Steps to reproduce

Normal steps to install CustTermux-JioTVGo on any android TV with OTT Navigator as an IPTV player

### Relevant log output

```shell
no logs output
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Will be solved in #378
