### ISSUE TITLE
bug: Gujarati NEWS chanels aren't working

### ISSUE THREAD

**Issue by Dhruvpatel2112** [rabilrbl/jiotv_go#383]
### Bug description

All of gujarati Tv Chennels aren't working on quality high and auto.please fix it in kodi iptv. ABP ASmita Gujarati.

### Steps to reproduce

open kodi , simple iptv then click abp asmita.

### Relevant log output

```shell
no output.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Kodi is not officially supported. Only OTT Navigator iptv client is supported
