### ISSUE TITLE
bug: Audio Language Set to Hindi, But Content Plays in Hindi

### ISSUE THREAD

**Issue by AyushBhagat151105** [rabilrbl/jiotv_go#384]
### Bug description

i find this bug on my mobile and my fire tv in that i surfing to find my favorite channel like history tv 18 or discovery but i show the problem i select Hindi channel to watch but its play English channel 

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

.

### Solution

.

### Additional context

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
@AyushBhagat151105 Steps to reproduce and screenshots must be present.
Will close this issue in few days if not updated
