### ISSUE TITLE
bug: otp not coming 

### ISSUE THREAD

**Issue by karanchawlaldh** [rabilrbl/jiotv_go#386]
### Bug description

I am using OnePlus y series tv,  jiotvgo universal app installed successfully, but otp is not coming after adding my phone number, please guide me 

### Steps to reproduce

Otp not coming 

### Relevant log output

```shell
OTP not coming
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Please update this issue with relevant logs, steps to reproduce and screenshots.
If not done, issue will be closed in few days
