### ISSUE TITLE
bug: disable_logout doesn't work as expected. 

### ISSUE THREAD

**Issue by GitCoderKD** [rabilrbl/jiotv_go#387]
### Bug description

in config I used disable_logout = true
but i am still able to logout from web.

### Steps to reproduce

Go to http://localhost:5001/
Click on logout button

### Relevant log output

```shell
n/a
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Fixed in v3.8.1
