### ISSUE TITLE
bug: Major channel's or not playing is Colors & Zee5 

### ISSUE THREAD

**Issue by vijay307** [rabilrbl/jiotv_go#410]
### Bug description

Major channel's or not playing is Colors & Zee5 

### Steps to reproduce

Major channel's or not playing is Colors & Zee5 

### Relevant log output

```shell
Major channel's or not playing is Colors & Zee5
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Fixed
