### ISSUE TITLE
bug: Error 451 Unavailable For Legal Reasons

### ISSUE THREAD

**Issue by geekguide** [rabilrbl/jiotv_go#419]
### Bug description

After Automatic Installation and login via otp it shows "an error occurred while loading this video" 
While Inspect m3u link i found "451 Unavailable For Legal Reasons"
i tried with other number too same issue
May i know how to solve this issue?
Thank you

### Steps to reproduce

 Go to http://192.168.1.3:8087/play/143 .....it ll throw an error

### Relevant log output

```shell
Status
451
Unavailable For Legal Reasons
VersionHTTP/1.1
Transferred259 B (0 B size)
Referrer Policystrict-origin-when-cross-origin
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Are u running JioTV Go on a VPS/Cloud ?
Second, your logs aren't helpful. Send appropriate logs from both terminal and jiotv_go.log file from ~/.jiotv_go

**Comment by geekguide** [comment]
No Bro I am using it on my android phone with termux installed
i tried to get jiotv_go.log  it says command not found

**Comment by rabilrbl** [comment]
Other users aren't facing this issue.
Closing. I suggest you chat with our community users in telegram at https://telegram.me/jiotv_go_chat
