### ISSUE TITLE
bug: zee major channels (zee tv, zee cinema, zee bangala etc and & picture all channels gone.

### ISSUE THREAD

**Issue by Nexus-Gits** [rabilrbl/jiotv_go#420]
### Bug description

zee major channels (zee tv, zee cinema, zee bangala etc and & picture all channels gone.

### Steps to reproduce

Use the Custtermux Jio tv Go.

### Relevant log output

```shell
zee major channels (zee tv, zee cinema, zee bangala etc and & picture all channels gone.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by prashantcruise** [comment]
try to re-fetch the code, I had faced same issue with the docker and after doing again pull latest and force deploy it was working.

Whats is showing in the logs ?
