### ISSUE TITLE
Zee channels are removed 

### ISSUE THREAD

**Issue by Bharath2207** [rabilrbl/jiotv_go#425]
### Bug description

Few channels from Zee are removed like Zee telugu.
Please add them.

### Steps to reproduce

You can see zee channels

### Relevant log output

```shell
I have no log
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Jio has removed zee channels. Ask Jio to add it back
