### ISSUE TITLE
feat: hotstar chanels are missing in m3u playlist

### ISSUE THREAD

**Issue by Dhruvpatel2112** [rabilrbl/jiotv_go#426]
### Feature description

Please update m3u playlist for hotstar channels, As ipl is coming in upcoming months.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
JioTV Doesn't support hotstar channels / live events.
