### ISSUE TITLE
feat: not working while server host

### ISSUE THREAD

**Issue by srkuna** [rabilrbl/jiotv_go#47]
### Feature description

Hello bro can you make it change so it can work for hosting i see on network it direct request url to jio is there anyway to request through server? Ip

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
The issue is realted to JioTV API blocking remote server requests. The issue shall be solved when proxy support is present in JioTV Go via #40
