### ISSUE TITLE
i can't access site with public ip

### ISSUE THREAD

**Issue by rajat99260** [rabilrbl/jiotv_go#5]

**Comment by rabilrbl** [comment]
Hi there,
Please send screenshots here with appropriate description
Also mention your device and architecture

**Comment by siddharthsky** [comment]
@rabilrbl @rajat99260 
The server is running on localhost:5001. As it is available locally. But if it was running on local device IP e.g. 192.168.1.91 then it is possible to access it from other devices in the same network. (e.g. Using phone as a server for hosting and using IPTV on TV.)

- I tried running server on localhost as well as local IP at the same time. It is working for Windows, Linux but sadly not on Termux. As it is failing to get IP address (/proc/net/route : Permission denied [Android 10+]).

**Comment by rabilrbl** [comment]
@siddharthsky I'll try to add optional cmd argument to specify host address

On termux, for me it sometimes works, other times I receive weird pointer exception error. However I was able run the server and access at localhost:5001

**Comment by siddharthsky** [comment]
[@rabilrb](https://github.com/rabilrbl)l Thank you

**Comment by krz123** [comment]
i try these steps in termux but understood me .
can you tell me the step properly. thank you

termux-setup-storage
mkdir $PREFIX/jiotv_go
cp ~/storage/downloads/<jiotv_go_bin> $PREFIX/jiotv_go
cd $PREFIX/jiotv_go
chmod +x <jiotv_go_bin>
./jiotv_go_bin

**Comment by rabilrbl** [comment]
Now You can run jiotv_go with following optional argument 
```bash
./jiotv_go "127.0.0.1:4998"
```
