### ISSUE TITLE
help needed regarding server host

### ISSUE THREAD

**Issue by krishnastunning** [rabilrbl/jiotv_go#9]
i want to host on server but i got it doesn't enable port 5001 on azure can you help me to fix

**Comment by rabilrbl** [comment]
Are you sure, this application can work outside Jio network?
Because, I haven't tested it.

Azure VM or Cloud functions?

**Comment by krishnastunning** [comment]
yes it work but need help regarding binding 5001 port with azure vm public ip so i can access with my public ip i wish you will me to update

**Comment by rabilrbl** [comment]
Go to firewall settings in azure portal for the VM
Then enable HTTP or HTTPS port either `80` or `443` if you ssl certificate
Give the optional argument for jiotv_go run command like below
`./jiotv_go ":port"`

you should see your application if launched sucessfully

**Comment by krishnastunning** [comment]
application run successfully but i don't see our script listening for port 80 or 443 or 5001 still it shows closed

**Comment by rabilrbl** [comment]
The error is likely related to JioTV API network blocking,
See #4

**Comment by krishnastunning** [comment]
i don't think it blocked by jio tv can you check refer to https://github.com/dhruv-2015/JIOTVServer he just help with 3500 port which work perfectly

**Comment by krishnastunning** [comment]
according to chat gpt i got sme thing which you may know and help us to solve
package main

import (
    "fmt"
    "net"
)

func main() {
    // Define the network address to listen on (e.g., ":8080" for port 8080 on all available network interfaces).
    address := ":8080"

    // Create a TCP listener on the specified address.
    listener, err := net.Listen("tcp", address)
    if err != nil {
        fmt.Println("Error:", err)
        return
    }
    defer listener.Close()

    fmt.Println("Listening on", address)

    for {
        // Accept incoming connections.
        conn, err := listener.Accept()
        if err != nil {
            fmt.Println("Error accepting connection:", err)
            continue
        }

        // Handle the connection in a separate goroutine.
        go handleConnection(conn)
    }
}

func handleConnection(conn net.Conn) {
    defer conn.Close()

    // Handle the incoming connection, for example, by reading and writing data.
    // You can customize this function to implement your desired behavior.
    // Here's a simple echo server example:
    buffer := make([]byte, 1024)
    for {
        n, err := conn.Read(buffer)
        if err != nil {
            fmt.Println("Error reading:", err)
            return
        }
        data := buffer[:n]
        fmt.Printf("Received: %s", data)
        _, err = conn.Write(data)
        if err != nil {
            fmt.Println("Error writing:", err)
            return
        }
    }
}

**Comment by rabilrbl** [comment]
> i don't think it blocked by jio tv can you check refer to https://github.com/dhruv-2015/JIOTVServer he just help with 3500 port which work perfectly

Yup, I'm still figuring out!

**Comment by krishnastunning** [comment]
any update ?

**Comment by rabilrbl** [comment]
Closing this for now, I'll be looking for a fix to access JioTV api with outside network in the future
